################################################################
##  Reinforcement Learning Trading Environment Configuration  ##
################################################################

# Bellow is the default configuration used by the environment.
# Uncomment and edit the wanted sections to use a different configuration.

# The environment that will be use.
#
# environment_id: "stock_exchange_engine:stock_exchange_engine_env-v0"

# Use the simulation engine.
#
# simulation: True

# Choose which api to use or use local data:
#
source: "local"

# Choose which index to use:
#
index: "AAPL"

# Input data folder path.
#
# data_path: ""

# Input data folder path.
#
start_date: "2019-01-01"
end_date: "2020-01-01"

# Data encoding
#
# data_encoding: "matrix"

# Render the environment
#
# render: False

# Stock Exchange parameters
#
initial_account: 1000
# commission: 0.05

################################################################
##             Specific Environment Configuration             ##
################################################################

# Bellow is the configuration used by a specific environment.
# Uncomment and edit the wanted sections to use a different configuration.

# reset_on_close: True

# random_ofs_on_reset: True
# reward_on_close: False
